### ISSUE TITLE
Errors are not propogated to child handlers.

### ISSUE THREAD

**Issue by shadowmint** [iron/mount#46]
Consider the following code:

    fn hello_world(_: &mut Request) -> IronResult<Response> {
      return Ok(Response::with(status::Ok, "Hello world!"));
    }

    fn fourzerofour(_: &mut Request) -> IronResult<Response> {
      return Ok(Response::with(status::NotFound, "No foo actions here"));
    }

    fn main() {

      // Actions
      let mut router = Router::new();
      router.get("/foo", hello_world);
      router.error(fourzerofour);

      // Combine middleware
      let mut mount = Mount::new();
      mount.mount("/foo", router);

      let iron = Iron::new(mount);
      iron.listen(Ipv4Addr(0, 0, 0, 0), 3000);
    }

You would naively expect the fourzerofour handler to be invoked for /foo/bar since /foo should be handled by the router. However, it is not, the default router for mount is invoked instead.

**Comment by reem** [comment]
And the error system isn't insane anymore, so this problem has just gone away entirely.
