### ISSUE TITLE
Mount doesn't seem to care what the HTTP method is.

### ISSUE THREAD

**Issue by ehiggs** [iron/mount#75]
If I mount a staticfile directory, making HEAD requests returns the file instead of just the metadata. It's not clear if this is a problem with mount or staticfile.

Example requests to try:

`curl -XGET localhost:3000/somefile.txt`

`curl -XHEAD localhost:3000/somefile.txt`

**Comment by reem** [comment]
Correct, checking the HTTP method is the responsibility of the Handlers within Mount - Mount is general purpose, and so is still usable even with nontraditional or custom methods.

I'd call this a problem with staticfile.
