### ISSUE TITLE
Conflict serving static files like robots.txt

### ISSUE THREAD

**Issue by snadon** [iron/mount#82]
I would like to learn how to serve robots.txt-like files without overriding my index ("/") route.

Code example:

```
let mut mount = Mount::new();
mount
    .mount("/images/", Static::new(Path::new("src/static/assets/images")))
    .mount("/", Static::new(Path::new("src/static/etc"))) // serving files like robots.txt
    .mount("/", chain); // conflicting with previous mount
```

**Comment by Kerosene2000** [comment]
+1

**Comment by michaelsproul** [comment]
You could probably use Iron's router for this:

https://github.com/iron/router

**Comment by untitaker** [comment]
Yeah you need router for that.

There has been some demand for a variant of `mount` that tries handlers until it encounters a response that isn't 404, but I'm not sure what to think of that idea. It seems super imperformant to me.
