### ISSUE TITLE
Mount behavior changed since 0.2.0 release

### ISSUE THREAD

**Issue by AtheMathmo** [iron/mount#87]
Hey all!

My apologies if this is user error but I've spent quite some time trying to work through it. I had some code which was working fine with iron v.0.3.0 and mount v0.1.0 but since moving to v0.2.0 it is non-functional (without compiler errors).

```rust
fn main() {
    let mut mount = Mount::new();

    // Mount the underlying server logic
    mount.mount("/models/",
                router!(
        get "/kmeans" => hello_world,
    ));

    Iron::new(mount).http(("0.0.0.0", 3000)).unwrap();
}
```

I'm then testing this code by GETting: `localhost:3000/models/kmeans` . This gives the expected response in v0.1.0 but in v0.2.0 I get a 404.

The handler here is just a simple `Ok(Response::with((iron::status::Ok, "Hello World")))`

As a side note. It would be really valuable to provide a CHANGELOG detailing what goes into each change. I'd fine it a lot easier to transition my code if this existed.

**Comment by Hoverbear** [comment]
A full example without the lines you removed:

```rust
extern crate iron;
extern crate mount;
#[macro_use] extern crate router;

use iron::{Iron, Request, Response, IronResult};
use iron::status;

use mount::Mount;

fn hello_world(req: &mut Request) -> IronResult<Response> {
    println!("Running send_hello handler, URL path: {:?}", req.url.path());
    Ok(Response::with((status::Ok, "Hello!")))
}

fn main() {
    let mut mount = Mount::new();

    // Mount the underlying server logic
    mount.mount("/models/",
        router!(
            get "/kmeans" => hello_world,
        )
    );

    Iron::new(mount).http(("0.0.0.0", 3000)).unwrap();
}

```

**Comment by AtheMathmo** [comment]
@Hoverbear thank you and my apologies for not including this to begin with.

Are you also seeing this error on your end? At this point I'm unsure if this is a bug or a change in behavior that I'm not accounting for.

Thanks again.

**Comment by Hoverbear** [comment]
@AtheMathmo Same issue here yes. I'm poking around.

**Comment by Hoverbear** [comment]
I feel this might be a problem with router.

**Comment by AtheMathmo** [comment]
I did have some other issues without router - I may or may not have been using staticfile then though?

It looks to me that this could be related to #88 ? 

I have a busy evening but can try to test a few more cases tomorrow (if you need me to).

**Comment by Hoverbear** [comment]
Hmm you're right. I wasn't able to find any issues with router either.

**Comment by Hoverbear** [comment]
Confirmed this is fixed by #85.

Necessary `Cargo.toml`:

```toml
[package]
name = "example"
version = "0.1.0"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]

[dependencies]
router = "*"
mount = { git = "https://github.com/iron/mount.git" }
logger = "*"
iron = "*"

```

**Comment by AtheMathmo** [comment]
Perfect, thanks for looking into this!

**Comment by Hoverbear** [comment]
Try this: https://crates.io/crates/mount/0.2.1

**Comment by AtheMathmo** [comment]
Working for me too. That was fast - thanks!
