### ISSUE TITLE
Paths no longer hidden

### ISSUE THREAD

**Issue by BourgondAries** [iron/mount#88]
Trying to compile the simple example, and curling to it doesn't yield the same result as in the readme:

```
$ curl http://localhost:3000/blocked/foo
Running intercept handler, URL path: ["foo"]
```

I get this:

```
$ curl http://localhost:3000/blocked/foo
Running intercept handler, URL path: ["blocked", "foo"]
```

Code is copied verbatim from the example.
Here is my `Cargo.toml`
```
iron = "0.4.0"
mount = "0.2.0"
```

Also the example code in the readme uses `path`, not `path()`, which is wrong.

### Edit
As I started debugging the library `mount = { path = ... }` seemed to work fine, but `mount = "0.2.0"` does not. The former actually hides the path, the latter does not. I think a version 0.2.1 is needed.

**Comment by AtheMathmo** [comment]
Looks related to #87 ?

I'd say it seems more like a yank and 0.2.1 is needed.

**Comment by Hoverbear** [comment]
Yes I think #85 was needed before release.

**Comment by Hoverbear** [comment]
https://crates.io/crates/mount/0.2.1 has been uploaded. Please try this.

**Comment by BourgondAries** [comment]
Works, thanks!
