### ISSUE TITLE
Clarification about globs.

### ISSUE THREAD

**Issue by ereichert** [iron/mount#91]
I'm attempting to create a mount as follows.

mnt.mount("/public/*.css", Static::new(Path::new("src/public/stylesheets")));

Then in my requests I'm using the following URL.

http://localhost:3000/public/main.css

The URL fails to match the glob.

I've worked on this over the last few days and the only other glob I've been able to match is "/public/main.css".

It seems that globs in the mount API are either not working correctly or it doesn't match true globs.

I have a work around planned for the time being but would love to know if I've misinterpreted what I'm seeing or the API.

**Comment by untitaker** [comment]
Mount matches by prefix, not globs. I believe you're looking for https://github.com/iron/router

**Comment by ereichert** [comment]
I had docs for router and mount up at the same time.  I got confused.  Thanks for pointing that out.

I can solve the problem using router and two mounts.  Is there any interest in adding glob support to mount?

**Comment by untitaker** [comment]
That's not possible, because mount needs to figure out what to strip from the beginning of the URL path. 

Why not just use staticfile + mount and use the directory structure from your filesystem in the URLs as well?

**Comment by ereichert** [comment]
> Why not just use staticfile + mount and use the directory structure from your filesystem in the URLs as well?

Because I see writing 

<script src="public/javascript/main.js"></script>

instead of

<script src="public/main.js"></script>

and others as inefficient given that I have a file extension on which I can key to direct the handler to the correct directory.

I admit up front it's a nitpicky thing.  I was more curious about what is possible more than anything else.
